### PR TITLE
feat: add netcoreapp3.1 target and update deps

### PR DESCRIPTION
**Pull request by alsami**
* Add additional target-framework `netcoreapp3.1` to test project and raise sdk-version in `global.json`
* Add test dependencies for `netcoreapp3.1` to test-project
* Update `Autofac.Extensions.DependencyInjection` to version `5.0.1-develop-00435`
* Update `Autofac.Multitenant` to version `5.0.0-develop-00267`
* Update `Microsoft.SourceLink.Github` to version `1.0.0`

### CODE REVIEW

**Comment by tillig** [comment]
Were there breaking changes or something requiring the extra target? I thought the point of stuff like netstandard and netcoreapp was to target the lowest common denominator and let the consumer choose something later if needed.

**Comment by alsami** [comment]
> Were there breaking changes or something requiring the extra target?

They are not. I just thought it would be nice to add them. I can also remove them from the source-project and have only the test-project targeting `netcoreapp3.1` as well if you don't mind?

That also wouldn't be necessary but it won't hurt to make sure that it's running on ASP.NET Core 3.1 as well.

**Comment by tillig** [comment]
I think for testing adding the target to the test project is fine. If there's no technical reason to add new targets to the library, let's not.

**Comment by alsami** [comment]
> I think for testing adding the target to the test project is fine.

Should be good now.

**Review by tillig — APPROVED** [review]
👍

**Pull request merged**
