### PR TITLE
New extension method to avoid Startup's static property (fixes #6)

### LINKED ISSUE #6: Multitenant setup not working with aspnetcore 2.2
I followed the aspnetcore multitenant documentation, but still getting default services picked up.  Below is code for configureServices. 

``` public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            var builder = new ContainerBuilder();
            builder.Populate(services);
            builder.RegisterType<HttpHeaderTenantIdentificationService>().As<ITenantIdentificationStrategy>();
            builder.RegisterType<DefaultSomeService>().As<ISomeService>();
            var container = builder.Build();

            var multiTenantContainer = new MultitenantContainer(container.Resolve<ITenantIdentificationStrategy>(), container);


            multiTenantContainer.ConfigureTenant("1", m =>
            {
                m.RegisterType<TestSomeService>()
                  .As<ISomeService>()
                  .InstancePerLifetimeScope();  
            });

            Startup.ApplicationContainer = multiTenantContainer;
            return new AutofacServiceProvider(multiTenantContainer);
        }
```

```public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseAutofacMultitenantRequestServices(() => Startup.ApplicationContainer)
                .UseStartup<Startup>();
    } 
 ```

### PR DESCRIPTION
**Pull request by joaope**

### CODE REVIEW

**Comment by tillig** [comment]
I think adding this looks fine, but before I take the PR it'd be helpful to revert changes that aren't strictly necessary for the addition of the function. For example, if we don't need to update dependency packages, we try not to so we can retain as much compatibility as possible. (Updating the Sandbox is fine, updating the actual library isn't good.) If we don't need to update the .NET Core SDK for a specific reason, we usually don't.

It also looks like the logic in the two methods is almost identical - could the `WebHostBuilder` extension call the `ServiceCollection` extension so the logic is centralized?

The self-hosted integration test thing is a good call. Not part of this PR, but I'm thinking it might be good to have that for each of the ASP.NET Core frameworks we support to ensure changes to the code still allow for back-compat with the others.

**Comment by joaope** [comment]
> It also looks like the logic in the two methods is almost identical - could the `WebHostBuilder` extension call the `ServiceCollection` extension so the logic is centralized?

Of course, good call. Done.

> If we don't need to update the .NET Core SDK for a specific reason, we usually don't.

Reverted.

> if we don't need to update dependency packages, we try not to so we can retain as much compatibility as possible

Just did it for the main package because if we only reference `Autofac.AspNetCore.Multitenant` the `Autofac` transitive dependency coming with it is old (4.0.0 I believe) and buggy with ASP Core `IOptions<T>`. We learned this the hard way as it was not obvious what the problem was and the fix is to directly reference a newer `Autofac` version which is not really needed.

The sandbox doesn't (shouldn't?) need any Autofac.* dependencies for example.

Now that I look at it, I'm not fixing it, because `Autofac` is a transitive of a transitive dependency on `Autofac.Multitenant`. So the fix is probably there.

I'm reverting the change.

> The self-hosted integration test thing is a good call. Not part of this PR, but I'm thinking it might be good to have that for each of the ASP.NET Core frameworks we support to ensure changes to the code still allow for back-compat with the others.

Not sure if this means I can keep the tests or not?

**Comment by tillig** [comment]
Correct, keep the tests. I was just musing out loud about how I like the tests and think at some point in the future we can expand the testing in this repo to use more of that.

**Comment by tillig** [comment]
This is spectacular, thanks for the great contribution! Pulling now. I'll let it build and get a 0.1 release out with it shortly.

**Pull request merged**
