### PR TITLE
feat: add support for .NET6

### LINKED ISSUE #41: .NET 6 update
* Target .NET 6
* Update CI / CD pipeline
* Maybe drop older frameworks? 2.1 is EOL

### PR DESCRIPTION
**Pull request by alsami**
* Add TFM `NET6.0`  to src- and test-project
* Update Sandbox sample for `NET5.0` to use `NET6.0` bc it can be used the same way
* Update build-files
* Update a few dependencies

Closes #41

### CODE REVIEW

**Review by tillig — APPROVED** [review]
LGTM - thanks!

**Comment by tillig** [comment]
I don't have time to cut a release today. It might be tomorrow or the next day. If someone else has time, awesome, otherwise it'll have to wait.

**Comment by alistairjevans** [comment]
I'm putting a release together now.

**Comment by alistairjevans** [comment]
https://github.com/autofac/Autofac.AspNetCore.Multitenant/releases/tag/v5.1.0

**Pull request merged**
