### PR TITLE
chore: add github issue templates

### PR DESCRIPTION
**Pull request by alsami**
* Add templates for new issues / feature-requests and things alike based on the once also used in Autofac repo

### CODE REVIEW

**Comment by alistairjevans** [comment]
I'm wondering if it's best to do this per-repository, or at a global organisation level, just to reduce our effort on updating them. 

Downside is increased complexity customising the templates for each repo.

Question for @tillig I think.

**Comment by alsami** [comment]
> Downside is increased complexity customising the templates for each repo.

Agree. Does this work on organization level? Only used to the once from gitlab, they only have per repository solution available.

**Comment by tillig** [comment]
Oh, wow, I didn't know [you can set this up at the org level](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file). Yeah, having this at the org level is probably better than having to do it for every repo.

I'll work on that.

**Comment by alsami** [comment]
Allright, will close both PRs then!

**Pull request closed without merging**
